version: '3'
services:
  regcenter:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: ./target/vzoo-regcenter
    restart: always
    ports:
      - "9999:9999"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
